baseURL = 'https://www.visualnovelwiki.org/'
languageCode = 'en-us'
title = 'Visual Novel Wiki'
theme = 'hugo-theme-relearn'

[params]
  themeVariant = 'zen-dark'

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'
